# Generated by Django 4.0.4 on 2022-05-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('rating', models.FloatField(verbose_name='rating')),
                ('voters', models.IntegerField(verbose_name='voters')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
            ],
        ),
    ]
